### PR TITLE
Fix trailling / in login URLs (rebased)

### PR DESCRIPTION
**Pull request by nolanlawson**
Rebased version of #62 so we can test in Travis.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Hm, why is Travis not testing this?

**Comment by nolanlawson** [comment]
OK, well now that it's green, and we have tests in Travis, I can ask that we please add a new test to confirm that the fix works. @sapk any chance you have the time for that? Thanks for your help so far.

**Comment by sapk** [comment]
I could look into it

**Comment by nolanlawson** [comment]
Yeah, I think this change would need a test to go along with it. If we can't think of a way to reproduce it, then I would rather play it safe and not merge. Thanks for understanding!

If you need help writing a test case, folks are usually happy to help in the Freenode #pouchdb IRC channel or in the PouchDB Slack room. :)

**Comment by staxmanade** [comment]
NOTE: I added some details here: https://github.com/nolanlawson/pouchdb-authentication/issues/39#issuecomment-216096007 Hopefully we can get to the bottom of this - it's really slowing my local prototyping :)

**Pull request closed without merging**
