### PR TITLE
send login data as JSON

### PR DESCRIPTION
**Pull request by timwis**
Set the content-type to `application/json` and send the login data as stringified JSON.

Per @skiqh's [work-around](https://github.com/nolanlawson/pouchdb-authentication/issues/111#issuecomment-242810853) in #111 

For anyone else with the issue in the meantime, you can use his fork:

`npm i --save https://github.com/skiqh/pouchdb-authentication.git\#patch-1`

### CODE REVIEW

**Comment by broerse** [comment]
@nolanlawson I also like to have this PR. Can also release a version for you.

**Comment by nolanlawson** [comment]
This passes the test suite, so I'm perfectly fine with this. Will do a release today. Thanks!

**Comment by nolanlawson** [comment]
published in 0.5.4

**Comment by broerse** [comment]
Thanks!

**Pull request merged**
