### PR TITLE
Remove JSON stringify in login(). It gets double encoded which breaks the login

### PR DESCRIPTION
**Pull request by Charrondev**
`pouchdb-ajax`  already runs `JSON.stringify` on the body of an ajax request it makes. As a result the body of the request sent from `.login(user, password, opts)` was being stringified twice, which broke the login. This is in response to #130 For example:

`var body = {name: "admin", password: "password"} // {name: "admin", password: "password"}`

`var encoded = JSON.stringify(body) // {name: "admin", password: "password"}`

`var doubleEncoded = JSON.stringify(encoded) // "{\"name\":\"admin\",\"password\":\"password\"}"`

### CODE REVIEW

**Comment by quarthex** [comment]
Workaround:

```js
db.login(username, password, {
  ajax: {
    body: { username: username, password: password }
  }
}, () => {})
```

**Comment by nolanlawson** [comment]
I'm sorry for taking so long to approve this PR. Could you please add a new test to capture the failure? I believe there is already a test that checks to see if `.login()` works correctly, so I'm not sure what this solves.

**Comment by Charrondev** [comment]
No problem. I should be able to add the test this weekend.

**Comment by quarthex** [comment]
pouchdb-ajax@6.0.3 already set the `json` option [here](https://github.com/pouchdb/pouchdb/blob/6.0.3/lib/index.js#L5379).
According to the request API and source code, the `body` option *should* be a JSON object and the `Content-Type` header does not need to be set, neither does the `Accept` header.
An important detail is that I ran the issue within a browser application (more specifically, the renderer thread of an electron application). Currently, the unit tests run within a Node.js context.

**Comment by Charrondev** [comment]
The issue I had (and the reason I made the pull request) is because it was erring in the electron renderer (I think Chromium 54?). I'll see if I can make it come up in a node context though.

**Comment by nolanlawson** [comment]
@quarthex You're right, I should add Travis tests for the browser, but I haven't had time. :(

**Comment by quarthex** [comment]
Why closing this PR? Does the issue got fixed?

**Pull request closed without merging**
