### PR TITLE
Fix trailing / in login URLs

### PR DESCRIPTION
**Pull request by sapk**
Other solution for #41 #39

### CODE REVIEW

**Comment by sapk** [comment]
In get 4 errors with the master branch for : 
 - http authentication Test signup (Headers is not defined)
 - http authentication "after each loop" for Test signup  (Headers is not defined)
 - http authentication Test login/logout (cannot read property 'should' of null)
 - http authentication Test wrong user for getUser (expected : not_found but got AssertionError)

With my little fix the 2 first are solved but maybe i got some thing wrong executing the tests.

**Comment by nolanlawson** [comment]
I'm working on making the tests a little easier to run, in which case we'll be able to see in Travis whether this passes or not. Thanks for the fix! :)

**Comment by nolanlawson** [comment]
See #74

**Comment by nolanlawson** [comment]
I'm sorry for the delay on this. Since nobody has offered to provide a test case to verify that the fix works, I will take time out to write one myself and merge this.

**Comment by nolanlawson** [comment]
Closing in favor of https://github.com/nolanlawson/pouchdb-authentication/pull/91

**Pull request closed without merging**
