### PR TITLE
skipSetup => skip_setup

### PR DESCRIPTION
**Pull request by broerse**

### CODE REVIEW

**Comment by broerse** [comment]
@nickcolley I was just reading https://pouchdb.com/api.html and it states skip_setup. I was reading this because I was wondering if I really need this: https://github.com/broerse/ember-cli-blog/blob/master/app/adapters/application.js#L22

**Comment by nolanlawson** [comment]
Thanks, `skip_setup` is indeed the new format.

**Comment by tarr11** [comment]
still says `skipSetup` 4 times on the home page

image

**Comment by broerse** [comment]
@tarr11 Thanks. If you can find the time please make a PR for this.

**Comment by tarr11** [comment]
@broerse  Done!  https://github.com/nolanlawson/pouchdb-authentication/pull/153

**Pull request merged**
