### PR TITLE
added .changeUsername API

### LINKED ISSUE #70: changeUsername API
@nolanlawson Would such thing make sense? I have an application where I'm using this plugin and each user identifies with its email. I'd like to be able to give users the possibility to update the email they use to log into the app. If it does, I may be able to submit a PR soon.

### PR DESCRIPTION
**Pull request by mciparelli**
fixes #70

### CODE REVIEW

**Comment by nolanlawson** [comment]
Hey, this looks awesome, except that unfortunately it's not passing the test. I admit I haven't been the best about getting automated Travis tests set up for this project, but you can test it by running `npm run dev` and then opening that URL in a browser.

I fixed the JSHint issues (https://github.com/nolanlawson/pouchdb-authentication/commit/f1aa195b6e6d01139a5229bb3c99c04eb89dab2c), but the test is still failing due to a conflict error in one of the tests. I'm using OS X and CouchDB 1.6.1.

**Comment by mciparelli** [comment]
No it's ok, I did run them but I guess there's something I haven't pushed or something like that, I'll give it another try

**Comment by nolanlawson** [comment]
OK, the tests are now in, so if you do `git fetch && git rebase origin/master` you should be able to re-test your PR. Sorry about that hassle!

**Comment by nolanlawson** [comment]
Also here are [the test instructions](https://github.com/nolanlawson/pouchdb-authentication#test-this-library).

**Comment by mciparelli** [comment]
It's weird. I have the tests passing in a local pouchdb-server. When I try to run in a local fresh CouchDB I get forbidden by design doc... even for the first test. And in travis CI change username fails with an error I cannot reproduce locally :confused:

**Comment by mciparelli** [comment]
Alright! Made them pass. BTW, I needed to add password as an argument so that it's possible to login with the new username.

**Comment by mciparelli** [comment]
Alright, the password requirement made no sense. Now the user is copied in its entirety apart from the `_rev` field. Tests pass.

**Comment by nolanlawson** [comment]
LGTM! Thanks. :)

**Pull request merged**
