### PR TITLE
skipSetup => skip_setup

### PR DESCRIPTION
**Pull request by broerse**

### CODE REVIEW

**Comment by nickcolley** [comment]
Hey @broerse thanks for the PR, what are you trying to solve here?

**Comment by broerse** [comment]
@nickcolley I was just reading https://pouchdb.com/api.html and it states `skip_setup`. I was reading this because I was wondering if I really need this: https://github.com/broerse/ember-cli-blog/blob/master/app/adapters/application.js#L22

**Comment by broerse** [comment]
@nickcolley I see I passed `skip_setup``2 times. Will make a new PR.

**Comment by broerse** [comment]
New PR https://github.com/nolanlawson/pouchdb-authentication/pull/123

**Pull request closed without merging**
