### PR TITLE
Add Cloudant Support

### PR DESCRIPTION
**Pull request by ronag**
Needs testing against regular CouchDB.

### CODE REVIEW

**Comment by nolanlawson** [comment]
I admit I'm not too keen to add Cloudant support to pouchdb-authentication. The goal was just to provide the thinnest possible layer on top of vanilla CouchDB.

Additionally, this PR seems to add a pretty hefty dependency because you need to include the browserified version of the Node `crypto` module (not sure how much that adds). Furthermore, it looks like your changes will work for Cloudant but will break for CouchDB. :scream: 

According to @willholley it seems [you have the option](https://github.com/nolanlawson/pouchdb-authentication/issues/22#issuecomment-83498126) of enabling CouchDB-style authentication within Cloudant. So that's one option.

I would also strongly encourage you to take this PR and turn it into a fork of this repository and publish it as `pouchdb-cloudant-authentication` (or whatever you want to call it :wink:), since it could definitely come in handy for Cloudant users. But I think I will reluctantly put my foot down and say that this plugin will never support Cloudant/Couchbase/other non-CouchDB authentication systems. I just prefer to keep it simple.

**Comment by willholley** [comment]
I think the PR is misnamed - this is really making pouchdb-authentication work against CouchDB <1.3, I think. Cloudant's CouchDB auth support predates server-side password hashing on user creation (i.e. what we had in CouchDB 1.2) so this would have to be done client side.

**Comment by ronag** [comment]
Renamed repo as suggested.

**Comment by BigBlueHat** [comment]
@nolanlawson would you be open to reconsider? Cloudant is a major part of the CouchDB ecosystem and where many people take their PouchDB apps.

It's true the code would be simpler if these patches weren't included, but support for this old-style / Cloudant auth comes at a complexity cost for the communities that use PouchDB--which is the greater cost when it comes to adoption, longevity, etc.

So...pretty please? :smile_cat:

**Comment by willholley** [comment]
@BigBlueHat Cloudant is imminently going to be compatible with CouchDB 2.0 (including the server-side hashing of passwords when creating new docs in _users). Hopefully that should make it compatible - ping me if you want an early preview and I can move your Cloudant account to a cluster containing a release candidate of the upcoming build.

**Comment by BigBlueHat** [comment]
@willholley fabulous to know! Pinging you on IRC.

@nolanlawson it'd still be fabulous to have this fix for the next N months until this future Cloudant becomes the current Cloudant.

**Comment by willholley** [comment]
I rolled up these changes into https://github.com/willholley/pouchdb-authentication-cloudant

**Pull request closed without merging**
