### PR TITLE
(#26) - Change Password

### PR DESCRIPTION
**Pull request by jo**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Cool beans - you added tests, documentation, and you even built it for me. You make it difficult to say "no" to a pull request, huh? :wink:

**Comment by jo** [comment]
:P

**Comment by nolanlawson** [comment]
Boo, jshint is failing! Well, it's really my fault for not adding Travis tests. Testing manually, will fix the missing semicolons, then I'll merge and publish.

**Comment by jo** [comment]
Thanks and sorry for those missing semicolons. I should have vaccinated myself against the semicolon-less style which I use everywhere else ;)

**Comment by nolanlawson** [comment]
I feel ya, man. I feel the same way whenever I submit PRs into semicolon-less land. ;)

Published as 0.4.0.

**Pull request merged**
