### PR TITLE
Small syntax change

### PR DESCRIPTION
**Pull request by RichardLitt**
Adding space before bracket.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks, I should set up a JSHint to do this stuff. :P

**Comment by nolanlawson** [comment]
70ce0d598e6d4bb1b1751720102291344ab043e6

**Comment by RichardLitt** [comment]
I've been using [standard](https://github.com/feross/standard). Highly suggest it.

**Comment by nolanlawson** [comment]
Heh, been meaning to start using that as well, because I genuine am tired of these debates. :) Sadly most of PouchDB is in the semicolon-camp, so it would be a tough sell.

**Comment by RichardLitt** [comment]
I feel you. At some point, dictatorial decisions stating this is the style may be the way to go.

**Pull request closed without merging**
