### PR TITLE
Fixed: added semicolon at the end of the file

### PR DESCRIPTION
**Pull request by grammka**
Crash concatenate js files

### CODE REVIEW

**Comment by MMrko** [comment]
I came across this issue as well a while back. It did take some time to track it down. Bumping browserify to [5.0.0](https://github.com/substack/node-browserify/blob/master/changelog.markdown#500) would fix the semicolon issue but also requires changes to the build. If I find the time at some point I can look into this better. For now, I'm just using the minified version. Changing `bower.json` to point to the minified version could save people from the possible headache. Thanks for the awesome plugin btw! :)

**Comment by nolanlawson** [comment]
What concatenators out there aren't adding `\n` or `;` between files? I've got lots of plugins using this version of Browserify, so I'm loath to go out and fix them all.  >_<

**Comment by MMrko** [comment]
Well, this is definitely somewhat of an edge case. I'm using [gulp-useref](/jonkemp/gulp-useref), which in turn uses [gulp-concat](/wearefractal/gulp-concat) that passes `\n` as the separator for [concat-with-sourcemaps](/floridoo/concat-with-sourcemaps). In [some scenarios](https://github.com/airbnb/javascript/issues/44#issuecomment-25415141) a newline doesn't however guard against the missing semicolon issue.

**Comment by nolanlawson** [comment]
TBH I'm of the opinion that this is a bug in gulp-concat. Much easier to fix it in one build tool, as opposed to fixing it in every JS lib on the planet. :)

Sorry to be a bit stubborn, but I'm gonna close this one.

**Comment by nolanlawson** [comment]
I filed an issue on gulp-concat ^.

**Comment by MMrko** [comment]
Yup, I agree :)

**Pull request closed without merging**
